version: "2"
services:
  helen-node: 
    image: helen:0.0.1
    container_name: helen-node
    restart: always
    build: .
    ports: 
      - "5000:5000"
    depends_on:
      - helen-database
    environment:
      - DB_HOST=helen-database
      - DB_PORT=27017
      - DB_NAME=helen
      - DB_PROTOCOL=mongodb
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5000
      - DOMAIN_PROTOCOL=http
      - DOMAIN_HOST=127.0.0.1
      - DOMAIN_PORT=3000
      - NODE_ENV=development
      - PLATFORM=helen
  helen-database:
    container_name: helen-database
    image: mongo:4.0
    restart: always
    volumes:
      - ./db-data:/data/db
    ports:
      - "27018:27017"